### ISSUE TITLE
Error while package installing

### ISSUE THREAD

**Issue by Zhamalbek** [ZhymabekRoman/Platonus_API_Wrapper#2]
>python setup.py

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

осындай қате шығып тұр! не істесем болады?

**Comment by Zhamalbek** [comment]
error: no commands supplied

python setup.py install деп көрдім болмады

**Comment by Zhamalbek** [comment]
> > python setup.py
> 
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> or: setup.py --help [cmd1 cmd2 ...]
> or: setup.py --help-commands
> or: setup.py cmd --help
> 
> осындай қате шығып тұр! не істесем болады?

error: no commands supplied

**Comment by ZhymabekRoman** [comment]
Хмм, қызық. менде барлығы жақсы істеліп жатыр 
![image](https://user-images.githubusercontent.com/61125068/109930344-bfb1df80-7cf1-11eb-9b79-debe48f6c3bd.png)

**Comment by Zhamalbek** [comment]
менде 3,6 версия екен 3,9 орнатып корейін

**Comment by ZhymabekRoman** [comment]
Сізде Windows-пе?

**Comment by Zhamalbek** [comment]
Aha windows 7, 64x

**Comment by ZhymabekRoman** [comment]
Менде өкінішке орай, өзім көріп тексеретін Windows жоқ, тек қана Linux. Былай істеп көріңіз:
```
1) Мына сілтеме арқылы pip жүктеп алыңыз: https://bootstrap.pypa.io/get-pip.py
2) Жанағы жүктеген get-pip.py файылын орнатыңыз: python3 get-pip.py 
3) platonus-api-wrapper репозиториясын жұктеп алып:
    python3 ./setup.py build
    python3 ./setup.py install
```

**Comment by ZhymabekRoman** [comment]
Issue closing, due to non-activity
